// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp3_MVC.ModelsContext;

namespace Tp3_MVC.Migrations
{
    [DbContext(typeof(GroupDbContext))]
    partial class GroupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tp3_MVC.Models.Student", b =>
                {
                    b.Property<int>("codeStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("codeStudent")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnName("fullName")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("old")
                        .HasColumnName("old")
                        .HasColumnType("int");

                    b.HasKey("codeStudent");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
